### ISSUE TITLE
No newline after django tag

### ISSUE THREAD

**Issue by tissieres** [sezze/prettier-plugin-django-alpine#2]
Hello,

Thanks for this plugin. Is there a way to prevent this
```
{{ django }}abc
```
to be formatted like this:
```
{{ django }}
abc
```
It introduces a whitespace that is not wanted.

**Comment by sezze** [comment]
Thank you for reporting, I'll fix this as soon as possible! (within a month or so due to holidays coming up)

**Comment by tissieres** [comment]
If you can give me some hints in the meantime, I could maybe propose a PR to fix this.

**Comment by sezze** [comment]
You can probably do this :)
`{{ django|add:"abc" }}`

Or maybe this if it doesn't cause a new line
`{{ django }}{{ "abc" }}`

**Comment by tissieres** [comment]
Well, thanks for the suggestions :joy:  I'll wait for your fix thanks!

**Comment by tissieres** [comment]
Hi @sezze, sorry to bother you again but have you had some time to have a look on this issue?

**Comment by tissieres** [comment]
My bad, your plugin was not the culprit for this behaviour but this option: `--html-whitespace-sensitivity ignore`.

**Comment by sezze** [comment]
That's great to hear! I hadn't looked at this yet due to work tasks with higher priority. I may open this again so that this wouldn't be necessary, I feel like this shouldn't create a new line even with that option turned on.
