### ISSUE TITLE
Could you add an install tutorial without npm?

### ISSUE THREAD

**Issue by rakafo** [sezze/prettier-plugin-django-alpine#3]
Using only django I'd like to avoid npm since there's no need for it - prettier can be installed as a vscode extension. Could you guide, if possible, how to use your plugin without npm?

**Comment by sezze** [comment]
The vscode extension installs its own instance of prettier which uses node and npm internally. I don't know of a way to install plugins into the vscode extension without installing it locally, which requires npm.

It could be possible, but that support would have to be added by the prettier extension. This package should be installable like any other plugin, so if you find a way to install plugins directly into the extension, let me know. Sadly, I think it is not currently possible.

**Comment by rakafo** [comment]
Understood. I've since gone ahead and used npm as I lack the understanding of how to make it work otherwise.
